### ISSUE TITLE
Teacher dashboard new analysis

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-open-education-data#10]
Add analysis for teachers especially on qualified/certified, PTR, etc. Details coming soon.

**Comment by ghachey** [comment]
Qualified/Certified teachers analysis is present. PTR and other new stuff has not yet been added. Details coming later.

**Comment by ghachey** [comment]
@maratomega This work involved refining the dashboard with the latest changes. Refer to 

https://miemis-test.pacific-emis.org/#!/teachers/dashboard

This dashboard now downloads more data to support new disaggregations (e.g. by Region). While the old API continues to work to retrieve all necessary data you will need to call 

`/api/warehouse/teachercountx`

instead of

`/api/warehouse/teachercount`

**Comment by maratomega** [comment]
The order of components based on State/District

**Comment by ghachey** [comment]
> The order of components based on State/District

Order ideally are the same as those seen in the web app.

**Comment by ghachey** [comment]
Will consider this complete, new work will be detailed in other issues
