### ISSUE TITLE
Wrong filter in Schools dashboard

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-open-education-data#14]
In the School dashboard (and possible others as well) the School Levels filter is incorrect. It is using levels but it should be schoolTypeLevels. This is a bug and needs to be addressed.

**Comment by marinaomega** [comment]
Issue is fixed in the latest build 1.1.4 37

**Comment by ghachey** [comment]
The fix is not working. Please check along side the FedEMIS online app to verify your expected results. For example, I filtered Schools by ECE-Grade 8 school type and there is no data while there should be some.

The actual filter was replaced with the correct one but the filtering is not correctly filtering the data.

**Comment by marinaomega** [comment]
I'm sorry, you are right. Now it's fixed

**Comment by ghachey** [comment]
Great, looking forward to the next build.

**Comment by marinaomega** [comment]
The fix should be included

**Comment by ghachey** [comment]
Working in latest

**Comment by ghachey** [comment]
Actually, this is still not working correctly. Some filters work correctly and some not. Please verify with the online web app for *every* filter to produce the same exact results

**Comment by maratomega** [comment]
@ghachey Fixed

**Comment by ghachey** [comment]
Almost, but not quite functioning as the dashboards online. I believe this may be affecting all dashboards. You need to verify. But no need to rush this fix for the next release. We can still push the next release and you fix this eventually for the following release after that.

Note on the online web app? How the filters chosen do not become the only part of the chart but are instead "highlighted" All filters take effect and will reduce the amount of data in the chart, but not all. We can discuss this over a call in further details when the time come.

![Screenshot 2022-09-20 102740](https://user-images.githubusercontent.com/1091769/191153934-9d274f74-e102-48d3-b29b-53eb0ce632a0.jpg)

**Comment by ghachey** [comment]
The original issue reported here seems fixed. Another issue will be created for the comment in https://github.com/ghachey/pacific-open-education-data/issues/14#issuecomment-1251762641
