### ISSUE TITLE
Welcome page for user needed

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-open-education-data#15]
We need a more graceful startup of the app in context with bad Internet connection (common in Pacific Islands.) This would provide a way to "warn" the user that first time loading of the app may take a little longer and may even fail if server is offline. I think this could be achieved with an intermediate welcome screen and a bit of failure handling logic when starting the app. Feedback on this approach welcome.

Proposed workflow.

1) Splash screen no more then 2-3 seconds.

![Screenshot_20211021-150900](https://user-images.githubusercontent.com/1091769/138232816-3f42fd81-955b-4a4e-b528-2e31831b11f8.jpg)

2) Need an intermediate welcome screen here I think.

Top of screen could have a smaller version of the app logo from the splash screen. Then followed by the welcome message below.

"""
Welcome to the Pacific Open Education Data app. We designed this app in our on-going efforts to more widely disseminate our data into the hands of users including data analylists, department leaders, operational staff, academic researchers, consultants and others. It publishes a selection of statistics from as far back as we have data. The quality of data is significantly improved in more recent years.

Unlike a web application available to those with Internet and not optimized for mobiles, our app works on phones with or without the Internet. Phones are the most widely available devices in the Pacific Islands. To use the app offline you will need to be somewhere with the Internet to both Install the app and download the data.

Finally, due to the nature of this app which does require a good Internet connection to get started, bare in mind that you may encounter errors on bad Internet connections, especially when first installing and trying it out. This should be transient and the return of the good Internet should get things working.

Participating Pacific Islands countries are included below. You can select one to access the data and/or you can also directly download data for any country for offline usage.

[LIST COUNTRIES]

[CHECKBOX] Skip this welcome page on future access.
"""

The failure logic in this welcome screen should be something like this. On country select (see [LIST COUNTRIES] above). try reaching server. If successful process to the dashboard for that country. If any issue display "Error in reaching FedEMIS server to get data. Please try again in a little while".

3) Actual dashboards screen for chosen country.

Adjust the top right menu of following screenshot to the new with an additional item "Back to main page".

![Screenshot_20211021-150906](https://user-images.githubusercontent.com/1091769/138232834-7576b08e-70e8-479e-9e41-6cc8b9276822.jpg)

**Comment by marinaomega** [comment]
Hi @ghachey 
We prepared the design of the Welcome screen, could you please review it? 
We've got 2 questions here: 

1. Can user continue using the app without choosing the country?
2. Point 3 "Adjust the top right menu of following screenshot to the new with an additional item "Back to main page"." What main page is meant here, could you please specify? Do I get it right, that Main page will become the one where user will choose the country?
![Welcome screen](https://user-images.githubusercontent.com/93191907/174296378-2ec0d26e-dc9e-4546-8dba-fd6078176ce3.png)

**Comment by ghachey** [comment]
Hi @marinaomega 

1. Where would the user go without choosing the country? A default country? I think perhaps we need to choose a country to proceed.
2. Yes, the main page will become the new Welcome page. But then this opens the question "what about users that check skip this welcome page on future access?" So perhaps it should still be possible to switch country once the app is started inside a specific country (just like it is now).

I'm open to suggestions here how this can be made smooth for users.

**Comment by marinaomega** [comment]
Hi @ghachey ,

Right, we agree that we should definitely have an option to choose a country to proceed. 

As for the Welcome page, we would suggest to add Onboarding screens instead of one big screen with long text, like this it will be easier for the user to read important info about the app and we'll have different illustrations for the first 3 screens which will describe the corresponding paragraph. I attach an example for your reference
![Onbarding](https://user-images.githubusercontent.com/93191907/174785655-7d49e936-eec0-4585-a668-fa42060aca57.png)

**Comment by ghachey** [comment]
Hi @marinaomega this looks good. You can proceed with  this idea.

**Comment by ghachey** [comment]
Feedback on the latest build. Please edit all the welcome pages like below. I have fixed a few errors.

Welcome to the Pacific Open Education Data app. We designed this app as part of our on-going efforts to more widely disseminate our data into the hands of interested users such as school teachers/principals, data analysts, government department leaders, operational staff, academic researchers, consultants and others. The quality of data is significantly improved in more recent years.

Unlike a web application available to those with Internet only and not optimized for mobile devices, our app works on phones with or without the Internet. Phones are the most widely available devices in the Pacific Islands. To use the app offline you will first need to be somewhere with the Internet for the installation of the app and to download the data.

Finally, since this app does need the Internet to load data from our servers, it is possible to encounter errors on bad Internet connections. This should be transient and the return to a good Internet connection should get things working. If you are located in a location with unreliable Internet or no Internet at all it is recommended to download all the data needed when on a good Internet. 

Participating Pacific Islands countries are included below. You can select one to access the data and/or you can also directly download data for any country for offline usage. A user guide is available online at https://docs.pacific-emis.org/doku.php?id=poed_user_manual.

**Comment by maratomega** [comment]
@ghachey Ready for review

**Comment by ghachey** [comment]
@maratomega is there a reason why the link is unclickable? Or at least some way to copy it?


![Screenshot 2022-09-20 100105](https://user-images.githubusercontent.com/1091769/191151028-c600c98e-8712-4c3e-92db-8f50c9619de0.jpg)

**Comment by ghachey** [comment]
This issue seems all good now.
