### ISSUE TITLE
WASH data missing in dashboard

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-open-education-data#16]
In FedEMIS there is not Toilet and Water data shown in the chart.

![wash-1](https://user-images.githubusercontent.com/1091769/139384176-53a5711f-1f16-4f3e-bc3a-aa3d3283e968.jpg)

But there is in the system as shown in the online web app.

![wash-3](https://user-images.githubusercontent.com/1091769/139384188-f0ed973c-5c52-4461-a8af-7fb0accd839c.jpg)

It seems to work correctly in MIEMIS.

![wash-2](https://user-images.githubusercontent.com/1091769/139384194-6b02ab2b-6d65-4f30-9530-1d889e569154.jpg)

**Comment by marinaomega** [comment]
We are displaying the same chart actually. Though in the app in one screen we can show 11 first lines, others are scrollable. In this case the first part of the chart is empty, that's the reason. As a solution we can hide the empty lines and display the chart starting from the place where there is some data. Or we can add animation to scroll to the 1st filled lines. What do you think?

**Comment by ghachey** [comment]
OK, I see. This is not clear for a user as I did not think of scrolling there. You suggestions are ok. Display only those with data for now, easier.

**Comment by marinaomega** [comment]
Ok!

**Comment by marinaomega** [comment]
It's fixed, please, check

**Comment by ghachey** [comment]
It's good. But 

1. why is the bars in the toilets so big and only showing two on my phone?
2. The water source ones displays more of them but I still feel it could fit a little more, no?
3. Also,  unless the user "knows" to scroll horizontally there is no indicators that this can be done? Is there no way to guide the users showing them it is horizontally scroll-able? Or perhaps we could in the next version add a note to the home page with this instruction.

**Comment by marinaomega** [comment]
Bars are fixed. I agree, we can guide users about the scrolling in the next version. I will consult with our designer what's the best way to do it in terms of UX

**Comment by marinaomega** [comment]
![Clipboard - 8 ноября 2021 г , 14_53](https://user-images.githubusercontent.com/93191907/140738933-64c394dd-98cb-4347-a8f4-5850b6736793.png)

**Comment by ghachey** [comment]
Looks good.
