### ISSUE TITLE
Requested permissions on installation

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-open-education-data#21]
Can you explain the following permissions what they are and why they are needed?

![Screenshot_2022-08-11-11-12-51](https://user-images.githubusercontent.com/1091769/184059503-75c7c5d7-afbc-4d82-baa1-42976402de81.png)

**Comment by maratomega** [comment]
Prevent tablet from sleeping - At the moment of data uploading to make sure all data uploaded, so that the device is not blocked and download does not stop

Play Instore Referrer API - to collect the analytics about installations

**Comment by ghachey** [comment]
@maratomega is there a way we can tell the user this? That is the only time it prevents from sleep?

**Comment by maratomega** [comment]
We can make a pop-up before it starts downloading, what message shall we show to the user?
This is the only time it prevents from sleep

**Comment by ghachey** [comment]
@maratomega I don't think we need to add this pop up. I think it should be fine. What is the play install referrer API?

**Comment by maratomega** [comment]
Play Install Referrer API - to collect the analytics about installations
