### ISSUE TITLE
No Internet and data better handling

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-open-education-data#22]
@maratomega I have a suggestion for an improvement. When a user tries to access a module with no previously fetched data we could improve the user experience a little. For example, I downloaded all the data for offline use *except* the special education module. So when I turn off my Internet and try to access Special Education I get the below. This is ok.

![Screenshot 2022-09-20 101324](https://user-images.githubusercontent.com/1091769/191152576-17b28919-3e8c-464b-91ae-0b1b28e408ea.jpg)

However, after clicking ok, I get into an infinite loop as shown below. Can instead of the spinning wheel in this particular case display a message. "No previously fetched data and no Internet. You can return to the home screen by clicking the back arrow at the top left."

![Screenshot 2022-09-20 101428](https://user-images.githubusercontent.com/1091769/191152749-0d6afe4f-dbd8-49da-a2e5-a4b94b068401.jpg)

What do you think?

**Comment by maratomega** [comment]
Great idea

**Comment by ghachey** [comment]
Working. Will close with PR.
