### ISSUE TITLE
Sort out any issues and warnings

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-open-education-data#24]
<img width="2103" alt="Screen Shot 2022-10-04 at 5 38 07 PM" src="https://user-images.githubusercontent.com/1091769/193787411-2b5925a9-35e6-45cb-a1a0-f4f8864b70cb.png">

**Comment by ghachey** [comment]
@maratomega What would be the process to test this out? Can you make sure a PR is done for all works into say branch "develop" and then I can pull branch develop to try this out. Please advise.

**Comment by ghachey** [comment]
@maratomega please provide update on progress towards this one.

**Comment by maratomega** [comment]
@ghachey addressed
