### ISSUE TITLE
Teachers never get the already loaded message

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-open-education-data#26]
No matter how often I download the Teachers module I never get the same message as others. I just get this again and again.

![Screenshot 2022-10-07 093416](https://user-images.githubusercontent.com/1091769/194447764-3a56f7da-88d5-4c52-b143-e1c0ccda110e.jpg)

Other modules I get this when data is already loaded. 

![Screenshot 2022-10-07 093449](https://user-images.githubusercontent.com/1091769/194448082-681df9ee-68c6-4bfa-81fe-7e75743756c4.jpg)

And I hope you also check for "new" data when data is already loaded. I will refer you to https://docs.pacific-emis.org/doku.php?id=emis_public_rest_api#etag to confirm to me you check whether there is new data or no.

**Comment by maratomega** [comment]
Hi @ghachey correct me if I'm wrong, it was an initial requirement to remove the identification by etag of the data downloaded. Do you want us to start using it again?
Not only Teachers a fetching without etag, but also All Indicators and Exams

**Comment by ghachey** [comment]
Why would it be an requirement to fetch without eTag? eTag is what is used to identify if there is any change in the data warehouse (thus change in the data). You most definitely need to pay attention to the eTag. It will work without eTag but it is much better to use eTag as you will be able to retrieve data again if it is changed. Otherwise, once retrieve by the app will may never refresh and remain un-updated thereafter.

**Comment by ghachey** [comment]
This issue seems fixed. Closing with the PR.
