### ISSUE TITLE
Unknown error occurred for individual schools

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-open-education-data#27]
I still get the Unknown error occurred when trying an individual school that was downloaded. Skip the unknown error and just display the following screen.

![Screenshot 2022-10-07 093950](https://user-images.githubusercontent.com/1091769/194448395-203deee4-3d3c-4e98-8fd6-1b9f7c911d4e.jpg)

Also, after click on ok on the information about no Internet we get this. Can we not have a nicer message like with global dashboards instead of never ending spinning wheels in a empty dashboard?

![Screenshot 2022-10-07 094131](https://user-images.githubusercontent.com/1091769/194448511-137debb9-78ca-47b8-b1f2-b9074b1f0cfc.jpg)

**Comment by maratomega** [comment]
replace The error message with
Information
An unknown error occurred. This may be a transient network error. Please return to the home page and try again in a few minutes.

**Comment by ghachey** [comment]
This issue seems reasonably fixed. Will be closed when we merge the PR
