### ISSUE TITLE
Special Education Dashboard not properly filtering data

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-open-education-data#28]
This is an old problem I reported and still persist. Check below. Only I filter by state (District) Yap and get filtered results. I also do not understand the numbers in the table below.

![Screenshot 2022-10-07 094807](https://user-images.githubusercontent.com/1091769/194449327-c1592c64-452a-4ab1-8f85-fba1dad74d41.jpg)

**Comment by ghachey** [comment]
@maratomega seems not working. Please refer to web application for correct behavior.

**Comment by maratomega** [comment]
> @maratomega seems not working. Please refer to web application for correct behavior.

Hi @ghachey Can you please describe in more details how suppose to behave, when we were fixing and testing this issue we did refer to web app.

**Comment by ghachey** [comment]
No break down by gender as shown below.

![Screenshot 2022-10-19 143315](https://user-images.githubusercontent.com/1091769/196615258-8d33a966-0415-4cc8-a05b-c44c78f573be.jpg)

**Comment by ghachey** [comment]
The cohort distribution never gets updated with the filters. Please observe the filter in the web app and you will see the whole cohort distribution chart widget get updated with any and all combination of filters.

![Screenshot 2022-10-19 143605](https://user-images.githubusercontent.com/1091769/196615479-240d9be7-3ec3-49d0-a230-6d0fdea2a1eb.jpg)

**Comment by ghachey** [comment]
@maratomega this seems like it still does not behave correctly. Please review by comparing thoroughly with the web app.

**Comment by maratomega** [comment]
@ghachey we are comparing with the web app using the following link https://fedemis.doe.fm/#!/schools/dashboard
and unfortunately, either we do not have access or the version we are using out dated, but we missing the Special Education section
![Clipboard - 10 мая 2023 г , 11_48](https://github.com/ghachey/pacific-open-education-data/assets/108275362/fda75fe6-642a-4e69-a84a-c7b7ca6478af)

**Comment by maratomega** [comment]
@ghachey we are comparing with the web app 
and unfortunately, we do not have permission to Read/View the Special Education section
![Permissions](https://github.com/ghachey/pacific-open-education-data/assets/108275362/3c3f048e-8207-4e15-8236-349acad65431)

**Comment by ghachey** [comment]
Are you using the production system? You now need to use the test system for these things. Access to the production system will no longer be allowed.

https://fedemis-test.pacific-emis.org/

You user should be the same.

**Comment by maratomega** [comment]
Understood, thanks for clarification!

**Comment by maratomega** [comment]
Hi @ghachey ,
While comparing the web app with mobile app and checking the data that we get from the backend, we realised that we get different data. For example, for 2023 in Disability section/Autism the web app shows 2 Male / 1 Female; we get from the backend 5 Male / 1 Female
[Pacific.docx](https://github.com/ghachey/pacific-open-education-data/files/11515151/Pacific.docx)

So the question is what data we should not use in mob app, based on which parameters/filters?
I hope it makes sense

**Comment by ghachey** [comment]
@maratomega I will update the test system with the same data as production to see if this explains your differences.

**Comment by maratomega** [comment]
Hi @ghachey did you have a chance to update the test system to clarify the above shared differences?

**Comment by ghachey** [comment]
@maratomega not yet. I will try in the days to come.

**Comment by ghachey** [comment]
@maratomega The test system was updated. There should be no difference in data as it comes from the same API. Please review this.

**Comment by ghachey** [comment]
@maratomega any updates on this?

**Comment by maratomega** [comment]
> @maratomega The test system was updated. There should be no difference in data as it comes from the same API. Please review this.

@ghachey addressed, based on the comment above

**Comment by ghachey** [comment]
@maratomega some minor feedback

- Most recent year should be at the top in the cohort distribution by year chart.
- In the filters, School Type in RMI is not called school type but is School Level. Refer back again to the vocab framework described in https://docs.pacific-emis.org/doku.php?id=emis_public_rest_api&s[]=vocab#vocab_lookup

That should be sufficient for this issue.

**Comment by ghachey** [comment]
@maratomega one more thing. What is this "No data" as shown below?

<img width="1588" alt="Screenshot 2023-11-30 114327" src="https://github.com/PacificEMIS/pacific-open-education-data/assets/1091769/72f64e14-cd22-414d-ac2e-6028d179459e">

**Comment by ghachey** [comment]
Considered done
