### ISSUE TITLE
Google Play's target API level requirements

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-open-education-data#33]
From Google:

> We've detected that 1 of your apps is targeting an old version of Android. To provide users with a safe and secure experience, Google Play requires all apps to meet target API level requirements before Aug 31, 2023. Action required: Update the following apps to target the latest Android version Pacific Open Education Data

**Comment by ghachey** [comment]
@maratomega Can we have a status on this one?

**Comment by maratomega** [comment]
@ghachey Addressed
