### ISSUE TITLE
Clear data and cache on upgrades

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-open-education-data#34]
I think it would be safer to automatically clear the app's data and cache when an upgrade is made available in the stores. I have seen little issues that could have been fixed simply by clearing those. I think they may have happened after upgrades with little conflicts in cached data, etc. To much trouble to tell public users to clear data and cache after an upgrade to avoid potential issues. Do this automatically somehow I think may avoid some issues.

**Comment by maratomega** [comment]
Hi @ghachey is there any chance that you could describe/provide more info about these **_little issues_** ?

**Comment by ghachey** [comment]
We don't remember clearly. One was about not finding the data and mine I saw once it was not working at all. Like starting the app but just like a blank or blue screen. Is it not recommended to clear cache automatically on new upgrades?

**Comment by maratomega** [comment]
It's better to fix any issues related to cache or old data, clearing cache would also work
We will try to reproduce the above mentioned issues, if it won't be possible we will just add functionality - auto clearing cache on new upgrade

**Comment by ghachey** [comment]
@maratomega status on this one?

**Comment by maratomega** [comment]
@ghachey Clearing cache  functionality was implemented,  to avoid redownloading of all the sections (Exams, Teachers, etc.) data clearing wasn't implemented.
Do you insist on implementing the Data clearing on upgrade as well?

**Comment by ghachey** [comment]
@maratomega what ever has th best chance of avoiding the conflicts of upgrade that was seen but some users.  We can start with this. Perhaps it would be a good idea to clear data *when there is a API change*. Some updates will require an API change and the data will come in slightly different shape. It would be a good idea to have some logic that clears the data also in such cases.

**Comment by maratomega** [comment]
Flag for clearing the data when API changes
