### ISSUE TITLE
Ability to customize the order of dashboard components through firebase

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-open-education-data#36]

**Comment by ghachey** [comment]
@maratomega I changed the order of the dashboard components in the firebase configuration. I put the Indicators one to come first. But I do not see this changed in the app. Is it because this is not implemented? Or because it takes a while for changes to take effect? Can you provide details on this?

**Comment by ghachey** [comment]
@maratomega this worked but it required a reinstallation of the app.

**Comment by maratomega** [comment]
@ghachey kindly let me know if we need to make any corrections from our side

**Comment by ghachey** [comment]
@maratomega can you ask the developers? Does this really need a re-installation to take effect? Or an upgrade? If it takes effect eventually without a user manual re-installation then that is fine. Like for example, if the order is changed in the firebase and then after say 24 hours the effect takes place in the app of users that is good. Or if it takes effect upon updating to the next version of the app then that is also good.

**Comment by maratomega** [comment]
@ghachey the team saying that it was suppose to update automatically, the Firebase remote config updates every 12 hours.

**Comment by ghachey** [comment]
Let's consider this complete.
