### ISSUE TITLE
Add emis_url setting

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-open-education-data#4]
Just like the feature for the Pacific Education Survey Tool (see https://github.com/ghachey/pacific-emis-education-survey-tool/issues/14) a flexible means to set the location of the EMIS shall be added. Refer to screeshot below. Currently this value is hard coded in the app. It shall be editable in the fetched firebase config. You can keep the hard coded one as fallback but the one fetched from firebase setting shall take precedence. This is required if the URL changes over time.

![emis_url-2](https://user-images.githubusercontent.com/1091769/120594902-2c18b800-c474-11eb-8954-de76b5f2505e.png)

**Comment by ghachey** [comment]
While you add the emis_url setting into the configuration please also pull out the hard coded login user into here as well.

![login](https://user-images.githubusercontent.com/1091769/132439669-2e7a3048-5d8e-4eaf-b633-fb44765c75ff.png)

**Comment by marinaomega** [comment]
Feature is implemented in the latest build 1.1.4 37 Though, for now we update the config while we start the app, so the change will not be visible immediately. Is that critical?

**Comment by ghachey** [comment]
I'm not sure I am following here. Perhaps let's get on a call to further clarify this.

**Comment by marinaomega** [comment]
In other words, this setting will be available either 10 hours after the change (as configuration is updated once in 10h) or immediately by reinstalling the app

**Comment by ghachey** [comment]
How about closing the app and re-starting it (not full re-installation)

**Comment by marinaomega** [comment]
It's updated with first installation and once in 5 hours. We can implement it when restaring the app/closing the app but no more often than once in 2 hours

**Comment by ghachey** [comment]
I think this is all good.
