### ISSUE TITLE
Option to download individual school data

### ISSUE THREAD

**Issue by ghachey** [ghachey/pacific-open-education-data#7]
Option to download individual school in addition to the Download all schools option

**Comment by marinaomega** [comment]
Hi @ghachey , please, review the design:
![School data download](https://user-images.githubusercontent.com/93191907/175492031-2f5b72e8-8f91-4a2c-9ef1-d6228e3ad2b3.png)
User can select all schools/one school/several schools

**Comment by marinaomega** [comment]
We also suggest improving the Menu to choose a country:
![1HUTVvTG](https://user-images.githubusercontent.com/93191907/175505142-878d0860-f566-41f2-9248-bdb3f334596b.png)

**Comment by ghachey** [comment]
Hi @marinaomega 

The design for the selection of schools looks pretty good.

The  new design to choose the country also ok. Perhaps change the color of the offline flag to red.

**Comment by marinaomega** [comment]
@ghachey I guess, if we make it red, it will be read as some error, but we need to show that the data was successfully downloaded, that's why green is used. What do you think?

**Comment by ghachey** [comment]
@marinaomega Ho I see. I thought it was indicating that the server was offline and that the data was not downloadable. You actually indicate that it was fully downloaded, I see now. Then perhaps the word offline might be a bit confusing. How about we keep green and use the word "Downloaded" or "Download complete". But this also could be a bit misleading. Because just because the download is complete does not mean there is no new data. So did you plan for a check on the data? The warehouse API call actually return some value indicating whether or not the data has changed from the last call. You'll have to review the API documentation but it is possible to know whether there was any change in the data warehouse. Refer to https://docs.pacific-emis.org/doku.php?id=emis_public_rest_api#etag

Ideally with this sort of feedback to the user it would be good to show

- Process of download of existing data (as you do now)
- But also whether any new data is available. Perhaps just a simple reminder to re-download all data every year or so is the simplest. The best would be to periodically, in the background, look for an Internet connection and for whatever country there is downloaded data, check for any changes in the data warehouse and notify user when there if somehow.

**Comment by marinaomega** [comment]
@ghachey Correct, we'll change the word to "Downloaded". If we have new data or data was not fully downloaded, we'll display "Update"

**Comment by maratomega** [comment]
Hi @ghachey  few more words about Download individual school option:
The reason I have asked about this screen/feature Option to download individual school data, is because we have came out with more user-friendly design of it. Please take a look at the attached images.

As you can see, a new version has few changes: Choose country - we added Check mark to show that this specific country selected; Download data - now user can choose what data he wants to download (Exams, Teachers, Individual schools, etc.), Individual Schools now has an option to open in new screen the list of schools to choose from. 

![Download Data, Select Schools](https://user-images.githubusercontent.com/108275362/177575367-4a26209d-da4f-441b-a43b-236081f49b4a.PNG)

![Home screen, choose country](https://user-images.githubusercontent.com/108275362/177575326-ae1cc9d4-d693-4997-859d-14bd6f6c1066.PNG)

**Comment by ghachey** [comment]
@maratomega this all looks great. You can continue with this design refinement.

**Comment by ghachey** [comment]
Feedback on the latest build. I see an error when I try to Download the Schools data. The same error with individual schools. The error is below. Perhaps this is valid feedback but it should not look like an error if it is. Please can you check this out.

![Screenshot_20220721-144213](https://user-images.githubusercontent.com/1091769/180293329-671576d2-698a-463d-848f-250b1cfb04b0.jpg)
![Screenshot_20220721-144050](https://user-images.githubusercontent.com/1091769/180293332-6b3de643-d0e6-43ae-a4ce-5143cb47dfd5.jpg)

**Comment by maratomega** [comment]
Hi @ghachey Thanks for the feedback, so what do you suggest? To make it as a note that that was downloaded already? Can you please share more details
We can ignore it, if that works for you

**Comment by ghachey** [comment]
Hi @maratomega But I had not previously downloaded anything?! This was on the first try. But it does look like the data was somehow downloaded as then I disconnected my Internet I can access Schools so perhaps I had it downloaded somehow. So a couple of things to consider:

- Why some return this message to user while others (Exam and Indicators) just reloads?
- The message returned is ok I think. However, I think it should look less like an error and more like information. So change the red exclamation point to blue. And remove the string "Exception: " in the string "Exception: Data already loaded". So it should read "Data already loaded". Don't forget to look for any newer data too. Are you doing a check for this before saying data is already loaded?

**Comment by ghachey** [comment]
@maratomega this has not yet been addressed. As above, for the following screenshot, we need something more user friendly than a scary red error message. I suggested above already in previous comment second bullet.

![Screenshot 2022-09-20 100502](https://user-images.githubusercontent.com/1091769/191151811-3de8e99c-ebc7-42dc-a0a2-6c4fa831b9c6.jpg)

**Comment by ghachey** [comment]
This seems ok now.
